name: Build and Export n8n Runner Image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # 支持手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          # 构建镜像并打上标签
          docker build -t n8n-custom-runner:latest .

      - name: Save and Compress Image
        run: |
          # 保存并直接压缩，减小文件体积
          docker save n8n-custom-runner:latest | gzip > n8n-custom-runner.tar.gz

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: n8n-runner-package
          path: n8n-custom-runner.tar.gz

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: n8n-runner-tarball
          path: n8n-runner.tar
          retention-days: 7 # 在 GitHub 上保留 7 天
