name: Download Ansible for CentOS 7 Offline

on:
  workflow_dispatch: # 手动触发执行

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: centos:7 # 核心：使用与目标环境一致的镜像

    steps:
      - name: Prepare Repository and Tools
        run: |
          # 安装 epel 源以获取 ansible
          yum install -y epel-release
          # 安装下载工具
          yum install -y yum-utils
          mkdir /opt/ansible-offline

      - name: Download Ansible and Dependencies
        run: |
          # 仅下载依赖，不安装
          # --resolve 解决依赖，--destdir 指定存放目录
          yumdownloader --resolve --destdir=/opt/ansible-offline ansible

      - name: Tar Files
        run: |
          tar -czvf ansible-centos7-offline.tar.gz -C /opt ansible-offline

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ansible-offline-package
          path: ansible-centos7-offline.tar.gz
